### ISSUE TITLE
Visulaization of ITSM AttnPool

### ISSUE THREAD

**Issue by xushilin1** [xmed-lab/ICLIP#1]
Hi, @Eli-YiLi, Thanks for your interesting and outstanding project; I hope ICLR-2023 will accept it.

For simplicity， i will ignore the normalization progress of image tokens.

In the Eq. 3 in this paper, we will have ISTM through this $\hat{M} = X_{1:, :} \times Y^T= (f_i(x)\cdot \phi_i)_{1:, :} \times Y^T$. 

For  ISTM MaxPool, we will get $\hat{M}$ by $\hat{M} =(f_s(x)_{1:, :} \odot A \cdot \hat{\phi_i}) \times Y^T$.

But I am not clear on how to calculate ISTM AttnPool, that is, i don't know how to use class token in  $\hat{M} = X_{1:, :} \times Y^T$

**Comment by Eli-YiLi** [comment]
Note that the feature map X1:,: is normalized in feature dimension (x.norm(-1)).
So the attention map is not kept after norm during test. And you can ignore A in test.
In face, the attention is only used in training to learn a good linear projection.

Thus, the difference among AttnPool, MaxPool, AvgPool and MMP is the pair of linear projection.
And all the methods use X1:,: x YT, with different phi.

Besides, If you don't want to retrain the model to get the phi, you are suggested to use the reversed ITSM in Eq.5,
which is easy to reproduce.
